name: Metrics
on:
  schedule: [{cron: "0 */4 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: sexnine/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: sexnine
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Australia/Sydney
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%